npmPublishRegistry: "https://npm.pkg.github.com"

npmScopes:
  tensor-hq:
    npmAlwaysAuth: true
    npmAuthToken: "${GH_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@metaplex-foundation/mpl-candy-guard@*":
    dependencies:
      debug: "*"
  debug@*:
    dependencies:
      supports-color: "*"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
