name: Build Rust Client

on:
  workflow_call:
    inputs:
      rust:
        type: string
      solana:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.75.0
        required: true
        type: string
      solana:
        description: Solana version
        default: 1.17.22
        required: true
        type: string

env:
  CACHE: true
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  build_sdk:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: tensor-foundation/actions/ssh-agent@v2
        with:
          key: |
            ${{ secrets.ESCROW_KEY }}
            ${{ secrets.TOOLBOX_KEY }}
            ${{ secrets.WHITELIST_KEY }}

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: tensor-foundation/actions/install-rust@v2
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: tensor-foundation/actions/install-solana@v2
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache Rust client test dependencies
        uses: tensor-foundation/actions/cache-crate@v2
        with:
          folder: ./clients/rust
          key: rust-client-test

      - name: Build Rust client
        shell: bash
        working-directory: clients/rust
        run: cargo build --all-features --release

      - name: Upload Rust client builds
        uses: actions/upload-artifact@v4
        with:
          name: rust-client-builds
          # First wildcard ensures exported paths are consistently under the clients folder.
          path: ./clients/rust/targe*/release/*marketplace*
          if-no-files-found: error
