name: Build Programs

on:
  workflow_call:
    inputs:
      rust:
        type: string
      solana:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.75.0
        required: true
        type: string
      solana:
        description: Solana version
        default: 1.17.22
        required: true
        type: string

env:
  CACHE: true

jobs:
  build_programs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: tensor-foundation/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: tensor-foundation/actions/install-solana@v1
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: tensor-foundation/actions/cache-crate@v1
        with:
          folder: '.'
          key: programs

      - name: Build programs
        shell: bash
        working-directory: scripts/program
        run: ./build.sh
        env:
          PROGRAMS: ${{ env.PROGRAMS }}

      - name: Upload program builds
        uses: actions/upload-artifact@v4
        with:
          name: program-builds
          # First wildcard ensures exported paths are consistently under the programs folder.
          path: ./targe*/deploy/*.so
          if-no-files-found: error
