name: Build Programs

on:
  workflow_call:
    inputs:
      rust:
        type: string
      solana:
        type: string
      node:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.75.0
        required: true
        type: string
      solana:
        description: Solana version
        default: 1.17.22
        required: true
        type: string
      node:
        description: Node version
        default: 20.x
        required: true
        type: string

env:
  CACHE: true

jobs:
  build_programs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: tensor-foundation/actions/install-rust@v2
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Solana
        uses: tensor-foundation/actions/install-solana@v2
        with:
          version: ${{ inputs.solana || env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install Node.js
        uses: tensor-foundation/actions/install-node-with-pnpm@v2
        with:
          version: ${{ inputs.node || env.NODE_VERSION }}
          cache: ${{ env.CACHE }}
          dependencies: true

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: tensor-foundation/actions/cache-crate@v2
        with:
          folder: '.'
          key: programs

      - name: Build programs
        shell: bash
        run: pnpm programs:build

      - name: Upload programs build
        uses: actions/upload-artifact@v4
        with:
          name: programs-build
          # First wildcard ensures exported paths are consistently under the programs folder.
          path: ./targe*/deploy/*.so
          if-no-files-found: error
