name: Test Rust Client

on:
  workflow_call:
    inputs:
      program_matrix:
        type: string

env:
  CACHE: true

jobs:
  test_sdk:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: tensor-foundation/actions/install-rust@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Solana
        uses: tensor-foundation/actions/install-solana@v1
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache Rust client test dependencies
        uses: tensor-foundation/actions/cache-crate@v1
        with:
          folder: ./clients/rust
          key: rust-client-test

      - name: Download program builds
        uses: actions/download-artifact@v4
        with:
          name: program-builds

      - name: Run tests
        shell: bash
        working-directory: scripts/client
        run: RUST_LOG=error ./test-rust.sh