name: Test Rust Client

on: [workflow_dispatch, workflow_call]

env:
  CACHE: true
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  test_sdk:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: tensor-foundation/actions/ssh-agent@v2
        with:
          key: |
            ${{ secrets.ESCROW_KEY }}
            ${{ secrets.TOOLBOX_KEY }}
            ${{ secrets.WHITELIST_KEY }}

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: tensor-foundation/actions/install-rust@v2
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Solana
        uses: tensor-foundation/actions/install-solana@v2
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install Node.js
        uses: tensor-foundation/actions/install-node-with-pnpm@v2
        with:
          version: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE }}
          dependencies: true

      - name: Cache Rust client test dependencies
        uses: tensor-foundation/actions/cache-crate@v2
        with:
          folder: ./clients/rust
          key: rust-client-test

      - name: Download program builds
        uses: actions/download-artifact@v4
        with:
          name: programs-build

      - name: Run tests
        shell: bash
        run: RUST_LOG=error pnpm clients:rust:test
