name: Test Programs

on:
  workflow_call:
    inputs:
      program_matrix:
        type: string

env:
  CACHE: true

jobs:
  test_programs:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program: ${{ fromJson(inputs.program_matrix) }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: tensor-foundation/actions/install-rust@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Solana
        uses: tensor-foundation/actions/install-solana@v1
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: tensor-foundation/actions/cache-crate@v1
        with:
          folder: '.'
          key: programs

      - name: Run cargo fmt
        uses: tensor-foundation/actions/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path ./${{ matrix.program }}/Cargo.toml -- --check

      - name: Run cargo clippy
        uses: tensor-foundation/actions/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features --no-deps --manifest-path ./${{ matrix.program }}/Cargo.toml

      - name: Run tests
        shell: bash
        working-directory: scripts/program
        run: RUST_LOG=error ./test.sh
        env:
          PROGRAM: ${{ matrix.program }}
